project:
  type: website
  output-dir: "docs"
website:
  title: "WOAH Datathon"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Challenges"
        href: challenges.qmd  
      - text: "Assessment criteria"
        href: criteria.qmd  
      - text: "FAQ"
        href: faq.qmd          
format:
  html:
    theme:
      - cosmo
      - brand
    # css: styles.css
    toc: true 
 


