project:
  type: website
  output-dir: "docs"
website:
  title: "WOAH Datathon"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Challenges"
        href: challenges.qmd  
format:
  html:
    theme:
      - cosmo
      - brand
    # css: styles.css
    toc: true
 


